'use client'

import { useConnect, useDisconnect, useReadContract, useWriteContract } from 'wagmi'
import { parseEther } from 'viem'
import { BTC_COLLATERAL_LOAN_ABI, CONTRACTS } from '@/contracts'
import { BTC_PUBKEY_PLACEHOLDER, NETWORK_CONFIG } from '@/constants'
import { useState, useEffect } from 'react'
import Link from 'next/link'
import { useWalletValidation } from '@/hooks/useWalletValidation'
import { switchToAnvil } from '@/utils/networkUtils'

function App() {
  const { validateWalletAndContracts, account } = useWalletValidation()
  const { connectors, connect, status, error } = useConnect()
  const { disconnect } = useDisconnect()



  // State to track if contracts are ready
  const [contractsReady, setContractsReady] = useState(false)
  
  // State to store contract addresses
  const [contractAddresses, setContractAddresses] = useState({
    ETHER_SWAP: '',
    BTC_COLLATERAL_LOAN: ''
  })

  // Monitor CONTRACTS changes
  useEffect(() => {
    // Check if all contracts are available
    if (CONTRACTS.ETHER_SWAP && CONTRACTS.BTC_COLLATERAL_LOAN) {
      setContractsReady(true)
      
      // Set contract addresses in state
      setContractAddresses({
        ETHER_SWAP: CONTRACTS.ETHER_SWAP,
        BTC_COLLATERAL_LOAN: CONTRACTS.BTC_COLLATERAL_LOAN
      })
    } else {
      setContractsReady(false)
    }
  }, [CONTRACTS.ETHER_SWAP, CONTRACTS.BTC_COLLATERAL_LOAN])

  // Loan interaction functions
  const { writeContract: requestLoan, isPending: requestLoanLoading, error: requestLoanError } = useWriteContract()
  const { writeContract: extendLoanOffer, isPending: offerLoading, error: offerError } = useWriteContract()
  const { writeContract: acceptLoanOffer, isPending: acceptLoading, error: acceptError } = useWriteContract()
  const { writeContract: attemptRepayment, isPending: repaymentLoading, error: repaymentError } = useWriteContract()
  const { writeContract: acceptRepayment, isPending: acceptRepaymentLoading, error: acceptRepaymentError } = useWriteContract()

  // Transaction status tracking
  const [lastTransactionHash, setLastTransactionHash] = useState<string | null>(null)
  const [transactionStatus, setTransactionStatus] = useState<'idle' | 'pending' | 'success' | 'error'>('idle')
  const [transactionError, setTransactionError] = useState<string | null>(null)

  // Loan data
  const { data: totalLoans, refetch: refetchLoans } = useReadContract({
    address: contractAddresses.BTC_COLLATERAL_LOAN as `0x${string}`,
    abi: BTC_COLLATERAL_LOAN_ABI,
    functionName: 'getTotalLoans',
    query: {
      enabled: !!contractAddresses.BTC_COLLATERAL_LOAN,
    },
  })

  const [loanAmount, setLoanAmount] = useState('0.1')
  const [collateralAmount, setCollateralAmount] = useState('0.12')
  const [selectedLoanId, setSelectedLoanId] = useState('0')
  // preimage hashes are generated by the preimageGenerator.sol script in the evmchain directory
  const [preimageHashBorrower, setPreimageHashBorrower] = useState<`0x${string}`>('0x4534f8f303eb5fc7175946b1c46772fa31bca38f724c1a0be97b9b0289431ee1')
  const [preimageHashLender, setPreimageHashLender] = useState<`0x${string}`>('0x646e58c6fbea3ac4750a2279d4b711fed954e3cb48319c630570e3143e4553e3')

  const handleRequestLoan = () => {
    if (!validateWalletAndContracts()) {
      return
    }

    if (!requestLoan) return

    requestLoan({
      address: contractAddresses.BTC_COLLATERAL_LOAN as `0x${string}`,
      abi: BTC_COLLATERAL_LOAN_ABI,
      functionName: 'requestLoan',
      args: [
        parseEther(loanAmount), // amount
        BTC_PUBKEY_PLACEHOLDER, // btcAddress
        BTC_PUBKEY_PLACEHOLDER, // btcPubkey
        preimageHashBorrower, // preimageHashBorrower
      ],
      value: BigInt('1000000000000000'), // PROCESSING_FEE (0.001 ETH in wei)
    })
  }

  const handleExtendLoanOffer = () => {
    if (!validateWalletAndContracts()) {
      return
    }

    if (!extendLoanOffer) return

    extendLoanOffer({
      address: contractAddresses.BTC_COLLATERAL_LOAN as `0x${string}`,
      abi: BTC_COLLATERAL_LOAN_ABI,
      functionName: 'extendLoanOffer',
      args: [
        BigInt(selectedLoanId), // loanId
        preimageHashBorrower, // preimageHashBorrower
        preimageHashLender, // preimageHashLender
      ],
      value: parseEther('0.11'), // loan + bond amount (10% of loan)
    })
  }

  const handleAcceptLoanOffer = () => {
    if (!validateWalletAndContracts()) {
      return
    }

    if (!acceptLoanOffer) return

    acceptLoanOffer({
      address: contractAddresses.BTC_COLLATERAL_LOAN as `0x${string}`,
      abi: BTC_COLLATERAL_LOAN_ABI,
      functionName: 'acceptLoanOffer',
      args: [
        BigInt(selectedLoanId), // loanId
        preimageHashBorrower, // preimageHashBorrower
      ],
    })
  }

  const handleAttemptRepayment = () => {
    if (!validateWalletAndContracts()) {
      return
    }

    if (!attemptRepayment) return

    attemptRepayment({
      address: contractAddresses.BTC_COLLATERAL_LOAN as `0x${string}`,
      abi: BTC_COLLATERAL_LOAN_ABI,
      functionName: 'attemptRepayment',
      args: [
        BigInt(selectedLoanId), // loanId
        preimageHashLender, // preimageHashLender
      ],
      value: parseEther(loanAmount), // repayment amount
    })
  }

  const handleAcceptRepayment = () => {
    if (!validateWalletAndContracts()) {
      return
    }

    if (!acceptRepayment) return

    acceptRepayment({
      address: contractAddresses.BTC_COLLATERAL_LOAN as `0x${string}`,
      abi: BTC_COLLATERAL_LOAN_ABI,
      functionName: 'acceptLoanRepayment',
      args: [
        BigInt(selectedLoanId), // loanId
        preimageHashLender, // preimageHashLender
      ],
    })
  }

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-4xl mx-auto px-4">
        <h1 className="text-3xl font-bold text-center mb-8 text-gray-900">
          Bitcoin-Collateralized Loan DApp
        </h1>
        


        {/* Connection Section */}
        <div className="bg-white rounded-lg shadow-md p-6 mb-6">
          <h2 className="text-xl font-semibold mb-4">Wallet Connection</h2>
          
          {/* Network Instructions */}
          <div className="mb-4 p-4 bg-blue-50 border border-blue-200 rounded-md">
            <h3 className="text-sm font-medium text-blue-800 mb-2">📋 Setup Instructions</h3>
            <div className="text-xs text-blue-700 space-y-1">
              <div>1. Start Anvil: <code className="bg-blue-100 px-1 rounded">anvil --mnemonic-seed-unsafe 2</code></div>
              <div>2. Connect your wallet (MetaMask, etc.)</div>
              <div>3. Add Anvil network: RPC URL <code className="bg-blue-100 px-1 rounded">{NETWORK_CONFIG.ANVIL.rpcUrl}</code>, Chain ID <code className="bg-blue-100 px-1 rounded">{NETWORK_CONFIG.ANVIL.chainId}</code></div>
              <div>4. Switch to Anvil network in your wallet</div>
            </div>
          </div>




          
          <div className="mb-4">
            <div className="text-sm text-gray-600 mb-2">
              Status: <span className="font-medium">{account.status}</span>
            </div>
            {account.addresses && (
              <div className="text-sm text-gray-600 mb-2">
                Address: <span className="font-mono text-xs">{account.addresses[0]}</span>
              </div>
            )}
            {account.chainId && (
              <div className="text-sm text-gray-600 mb-2">
                Chain ID: <span className="font-medium">{account.chainId}</span>
              </div>
            )}
          </div>

          {account.status === 'connected' ? (
            <div className="space-y-3">
              {/* Network Status */}
              {account.chainId !== NETWORK_CONFIG.ANVIL.chainId && (
                <div className="p-3 bg-yellow-50 border border-yellow-200 rounded-md">
                  <div className="text-sm text-yellow-800 mb-2">
                    ⚠️ You are connected to the wrong network. Please switch to Anvil (Chain ID: {NETWORK_CONFIG.ANVIL.chainId})
                  </div>
                  <button
                    onClick={switchToAnvil}
                    className="bg-yellow-500 hover:bg-yellow-600 text-white px-3 py-1 rounded text-xs transition-colors"
                  >
                    Add & Switch to Anvil
                  </button>
                </div>
              )}
              
              <button
                onClick={() => disconnect()}
                className="bg-red-500 hover:bg-red-600 text-white px-4 py-2 rounded-md transition-colors"
              >
                Disconnect
              </button>
            </div>
          ) : (
            <div className="space-y-2">
              {connectors.map((connector) => (
                <button
                  key={connector.uid}
                  onClick={() => connect({ connector })}
                  className="w-full bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-md transition-colors"
                >
                  Connect {connector.name}
                </button>
              ))}
            </div>
          )}
          
          {status && <div className="mt-2 text-sm text-gray-600">{status}</div>}
          {error && <div className="mt-2 text-sm text-red-600">{error.message}</div>}
          
          {/* Transaction Status Display */}
          {(requestLoanError || offerError || acceptError || repaymentError || acceptRepaymentError) && (
            <div className="mt-4 p-3 bg-red-50 border border-red-200 rounded-md">
              <h4 className="text-sm font-medium text-red-800 mb-2">❌ Transaction Error</h4>
              <div className="text-xs text-red-700 space-y-1">
                {requestLoanError && <div>Request Loan: {requestLoanError.message}</div>}
                {offerError && <div>Extend Offer: {offerError.message}</div>}
                {acceptError && <div>Accept Offer: {acceptError.message}</div>}
                {repaymentError && <div>Attempt Repayment: {repaymentError.message}</div>}
                {acceptRepaymentError && <div>Accept Repayment: {acceptRepaymentError.message}</div>}
              </div>
            </div>
          )}
        </div>

        {/* Contract Status */}
        {account.status === 'connected' && (
          <div className="bg-white rounded-lg shadow-md p-6 mb-6">
            <h2 className="text-xl font-semibold mb-4 text-gray-800">Contract Status</h2>
            
            {/* Contract Addresses Display */}
            <div className="p-4 bg-gray-50 border border-gray-200 rounded-lg mb-4">
              <h3 className="font-medium text-gray-800 mb-3">Deployed Contract Addresses</h3>
              <div className="space-y-2 text-sm">
                <div className="flex items-center justify-between">
                  <span className="font-medium text-gray-700">EtherSwap:</span>
                  <span className="font-mono text-xs bg-white px-2 py-1 rounded border text-gray-900">
                    {contractAddresses.ETHER_SWAP || 'Not deployed'}
                  </span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="font-medium text-gray-700">BtcCollateralLoan:</span>
                  <span className="font-mono text-xs bg-white px-2 py-1 rounded border text-gray-900">
                    {contractAddresses.BTC_COLLATERAL_LOAN || 'Not deployed'}
                  </span>
                </div>
              </div>
            </div>

            {/* Navigation to Role-Specific Pages */}
            {contractAddresses.BTC_COLLATERAL_LOAN && (
              <div className="p-4 bg-indigo-50 border border-indigo-200 rounded-lg">
                <h3 className="font-medium text-indigo-800 mb-3">Ready to Interact?</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <Link href="/lender" className="block">
                    <div className="p-4 bg-white border border-indigo-200 rounded-lg hover:border-indigo-400 transition-colors">
                      <h4 className="font-medium text-indigo-800 mb-2">🏦 Lender Dashboard</h4>
                      <p className="text-sm text-indigo-600">Manage loans, update parameters, and handle repayments</p>
                    </div>
                  </Link>
                  <Link href="/borrower" className="block">
                    <div className="p-4 bg-white border border-indigo-200 rounded-lg hover:border-indigo-400 transition-colors">
                      <h4 className="font-medium text-indigo-800 mb-2">💰 Borrower Dashboard</h4>
                      <p className="text-sm text-indigo-600">Request loans, accept offers, and manage repayments</p>
                    </div>
                  </Link>
                </div>
              </div>
            )}
          </div>
        )}

        {/* Loan Interaction Section */}
        {contractAddresses.BTC_COLLATERAL_LOAN && (
          <div className="bg-white rounded-lg shadow-md p-6 mb-6">
            <h3 className="text-lg font-medium mb-3">Loan Overview</h3>
            
            {/* Loan Statistics */}
            <div className="mb-4 p-3 bg-blue-50 rounded">
              <div className="text-sm text-blue-800">
                <div className="font-medium">Total Loans: {totalLoans ? Number(totalLoans) : 0}</div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

export default App
